version: '3'

services:

  nginx:
    image: fellipegarcias/nginx:1.21-alpine
    build: 
      context: ./nginx
      dockerfile: Dockerfile.prod
    container_name: nginx
    tty: true
    restart: always
    command: dockerize -wait tcp://node:5000 -timeout 20s /docker-entrypoint.sh nginx -g 'daemon off;'
    ports:
      - "8080:80"
    networks:
      - nodenetwork
    depends_on:
      - node

  node:
    image: fellipegarcias/node:17-alpine
    container_name: node
    tty: true
    restart: always
    command: dockerize -wait tcp://mariadb:3306 -timeout 20s docker-entrypoint.sh node index.js --port 5000
    build: 
      context: ./node
      dockerfile: Dockerfile.prod
    ports:
      - "5000:5000"
    volumes:
      - "./node/project:/var/www/html"
    networks:
      - nodenetwork
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.7.3
    restart: always
    command: --innodb-use-native-aio=0
    container_name: mariadb
    tty: true
    volumes:
      - "./mariadb:/var/lib/mysql"
    ports:
      - "3306:3306"
    networks:
      - nodenetwork
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root

networks:
  nodenetwork:
    driver: bridge



